---
name: QA-unit
run-name: QA unit testing in ${{ github.ref_name || 'default' }} branch

concurrency:
  group: qa-unit-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [develop, main]
    paths: ['code/**', '.github/workflows/code-*-QA_unit.yml']
  release:
    types:
      - published
jobs:
  unit-tests:      
    name: SonarQube / Unit Tests
    if: ${{ (github.event.pull_request.merged == true && (vars.DEVELOPMENT_FLOW != 'trunk-based-development' && (github.base_ref == 'develop' || startsWith(github.base_ref, 'develop-'))) ||
        (vars.DEVELOPMENT_FLOW == 'trunk-based-development' && (github.base_ref == 'main' || startsWith(github.base_ref, 'main-')))) ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'release' }}
    timeout-minutes: 30  
    runs-on: ubuntu-latest
    steps:
      - name: Check default branch
        id: default-branch
        run: |
          if [[ "${{ vars.DEVELOPMENT_FLOW }}" != "trunk-based-development" && "${{ github.event.repository.default_branch }}" == "develop" ]]; then
            echo "DEFAULT_BRANCH=develop" >> "$GITHUB_OUTPUT"
          else
            echo "DEFAULT_BRANCH=main" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Store project version
        id: pom-data
        run: |
          echo "app-version=$(xmllint --xpath "/*[name()='project']/*[name()='version']/text()" code/pom.xml)" >> "$GITHUB_OUTPUT"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven          
      - name: Run unit tests with release event
        if: github.event_name == 'release'
        working-directory: code
        run: |
            mvn -B clean verify -DskipEnforceSnapshots -Djacoco.skip=false -Damiga.jacoco -DskipITs -DfailIfNoTests=false -Dmaven.test.failure.ignore=false -
      - name: Run unit tests
        if: github.event_name != 'release'
        working-directory: code
        run: |
          mvn -B clean verify -Djacoco.skip=false -Damiga.jacoco -DskipITs -DfailIfNoTests=false -Dmaven.test.failure.ignore=false 

      - name: Sonar / Disable project-specific properties
        working-directory: ${{ github.workspace }}/code
        run: |
          find ./ -name pom.xml -exec sed -i 's/sonar./disabled./g' {} +          
          
      - name: Sonar / Configure input parameters
        working-directory: ${{ github.workspace }}/code
        run: |
          if [[ -f './jacoco-report-aggregate/pom.xml' ]]; then JACOCO_PARAM="-pl !jacoco-report-aggregate -Dsonar.skip=false"; else JACOCO_PARAM="-Dsonar.skip=false"; fi; \
          echo "JACOCO_SONAR_PARAM=$JACOCO_PARAM" >> "$GITHUB_ENV"
