---
name: QA-unit
run-name: QA unit testing in ${{ github.ref_name || 'default' }} branch

concurrency:
  group: qa-unit-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ATTACH_TARGET:
        description: Target platform to upload the generated report, it does not export results if empty. (p.e. jfrog)
        required: false
  pull_request:
    types: [closed]
    branches: ['develop', 'develop-*', 'main', 'main-*']
    paths: ['code/**', '.github/workflows/QA_unit.yml']
  release:
    types:
      - published
jobs:
  unit-tests:      
    name: SonarQube / Unit Tests
    if: ${{ (github.event.pull_request.merged == true && (vars.DEVELOPMENT_FLOW != 'trunk-based-development' && (github.base_ref == 'develop' || startsWith(github.base_ref, 'develop-'))) ||
        (vars.DEVELOPMENT_FLOW == 'trunk-based-development' && (github.base_ref == 'main' || startsWith(github.base_ref, 'main-')))) ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'release' }}
    timeout-minutes: 30  
    runs-on: [self-hosted]
    steps:
      - name: Check default branch
        id: default-branch
        run: |
          if [[ "${{ vars.DEVELOPMENT_FLOW }}" != "trunk-based-development" && "${{ github.event.repository.default_branch }}" == "develop" ]]; then
            echo "DEFAULT_BRANCH=develop" >> "$GITHUB_OUTPUT"
          else
            echo "DEFAULT_BRANCH=main" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
